# Generated by Django 4.2.27 on 2026-03-06 16:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_image', cloudinary.models.CloudinaryField(help_text='Original user-uploaded image', max_length=255, verbose_name='image')),
                ('webp_image', cloudinary.models.CloudinaryField(blank=True, help_text='WebP version (modern browsers, smallest size)', max_length=255, null=True, verbose_name='image')),
                ('compressed_image', cloudinary.models.CloudinaryField(blank=True, help_text='Compressed JPEG (fallback, older browsers)', max_length=255, null=True, verbose_name='image')),
                ('is_primary', models.BooleanField(default=False, help_text='Used as thumbnail')),
                ('order', models.IntegerField(default=0, help_text='Display order in gallery')),
                ('file_size_original', models.IntegerField(blank=True, help_text='Original file size in bytes', null=True)),
                ('file_size_webp', models.IntegerField(blank=True, help_text='WebP file size in bytes', null=True)),
                ('file_size_compressed', models.IntegerField(blank=True, help_text='Compressed file size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsedBikeListing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bike_model_id', models.IntegerField(blank=True, help_text='Reference ID to BikeModel in PostgreSQL', null=True)),
                ('custom_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_model', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('mileage', models.IntegerField(help_text='Total kilometers driven')),
                ('manufacturing_year', models.IntegerField()),
                ('registration_year', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('need_work', 'Needs Work')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, help_text='Seller contact number for this listing', max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('sports', 'Sports'), ('naked', 'Naked Sport'), ('cruiser', 'Cruiser'), ('commuter', 'Commuter'), ('scooter', 'Scooter'), ('adventure', 'Adventure'), ('cafe_racer', 'Cafe Racer'), ('offroad', 'Off-Road')], default='commuter', help_text='Bike category (e.g. Sports, Commuter)', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('sold', 'Sold'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
