# Generated by Django 4.2.27 on 2026-03-11 05:46

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0003_alter_bikemodel_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedBikeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('custom_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_model', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('mileage', models.IntegerField(help_text='Total kilometers driven')),
                ('manufacturing_year', models.IntegerField()),
                ('registration_year', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('need_work', 'Needs Work')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='Full address or area', max_length=255)),
                ('location_city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('location_area', models.CharField(blank=True, max_length=100, null=True)),
                ('location_division', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, help_text='Seller contact number', max_length=20, null=True)),
                ('has_accident_history', models.BooleanField(default=False)),
                ('engine_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('body_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('ownership_count', models.SmallIntegerField(default=1)),
                ('has_original_papers', models.BooleanField(default=True)),
                ('registration_type', models.CharField(blank=True, max_length=50, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('sports', 'Sports'), ('naked', 'Naked Sport'), ('cruiser', 'Cruiser'), ('commuter', 'Commuter'), ('scooter', 'Scooter'), ('adventure', 'Adventure'), ('cafe_racer', 'Cafe Racer'), ('offroad', 'Off-Road')], default='commuter', help_text='Bike category (e.g. Sports, Commuter)', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('sold', 'Sold'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_listings', to='bikes.bikemodel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listings', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_image', cloudinary.models.CloudinaryField(help_text='Original user-uploaded image', max_length=255, verbose_name='image')),
                ('webp_image', cloudinary.models.CloudinaryField(blank=True, help_text='WebP version (modern browsers, smallest size)', max_length=255, null=True, verbose_name='image')),
                ('compressed_image', cloudinary.models.CloudinaryField(blank=True, help_text='Compressed JPEG (fallback, older browsers)', max_length=255, null=True, verbose_name='image')),
                ('is_primary', models.BooleanField(default=False, help_text='Used as thumbnail')),
                ('order', models.IntegerField(default=0, help_text='Display order in gallery')),
                ('file_size_original', models.IntegerField(blank=True, help_text='Original file size in bytes', null=True)),
                ('file_size_webp', models.IntegerField(blank=True, help_text='WebP file size in bytes', null=True)),
                ('file_size_compressed', models.IntegerField(blank=True, help_text='Compressed file size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='Parent used bike listing', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.usedbikelisting')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['status', '-created_at'], name='marketplace_status_193e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['seller', '-created_at'], name='marketplace_seller__e8f48f_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['category', 'status'], name='marketplace_categor_0af89d_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['status', 'location_city', '-created_at'], name='marketplace_status_d22f63_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['price'], name='marketplace_price_a41ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['bike_model'], name='marketplace_bike_mo_96cb06_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'order'], name='marketplace_listing_0af853_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['is_primary'], name='marketplace_is_prim_ef9c50_idx'),
        ),
    ]
