# Generated by Django 4.2.27 on 2026-02-07 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedBikeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_model', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.IntegerField(help_text='Total kilometers driven')),
                ('manufacturing_year', models.IntegerField()),
                ('registration_year', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('need_work', 'Needs Work')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.bikemodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(help_text='Original user-uploaded image', upload_to='used-bikes/originals/%Y/%m/%d/')),
                ('webp_image', models.ImageField(blank=True, help_text='WebP version (modern browsers, smallest size)', null=True, upload_to='used-bikes/webp/%Y/%m/%d/')),
                ('compressed_image', models.ImageField(blank=True, help_text='Compressed JPEG (fallback, older browsers)', null=True, upload_to='used-bikes/compressed/%Y/%m/%d/')),
                ('is_primary', models.BooleanField(default=False, help_text='Used as thumbnail')),
                ('order', models.IntegerField(default=0, help_text='Display order in gallery')),
                ('file_size_original', models.IntegerField(blank=True, help_text='Original file size in bytes', null=True)),
                ('file_size_webp', models.IntegerField(blank=True, help_text='WebP file size in bytes', null=True)),
                ('file_size_compressed', models.IntegerField(blank=True, help_text='Compressed file size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='Parent used bike listing', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.usedbikelisting')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['status', '-created_at'], name='marketplace_status_193e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['seller', '-created_at'], name='marketplace_seller__e8f48f_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['location'], name='marketplace_locatio_62d4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'order'], name='marketplace_listing_0af853_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['is_primary'], name='marketplace_is_prim_ef9c50_idx'),
        ),
    ]
