# Generated by Django 4.2.28 on 2026-02-12 02:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='compressed_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Compressed JPEG (fallback, older browsers)', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='original_image',
            field=cloudinary.models.CloudinaryField(help_text='Original user-uploaded image', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='webp_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='WebP version (modern browsers, smallest size)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
