# Generated by Django 4.2.27 on 2026-03-06 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbikelisting',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedbikelisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(help_text='Parent used bike listing', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.usedbikelisting'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['status', '-created_at'], name='marketplace_status_193e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['seller', '-created_at'], name='marketplace_seller__e8f48f_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['category', 'status'], name='marketplace_categor_0af89d_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['location'], name='marketplace_locatio_62d4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['price'], name='marketplace_price_a41ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['bike_model_id'], name='marketplace_bike_mo_96cb06_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'order'], name='marketplace_listing_0af853_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['is_primary'], name='marketplace_is_prim_ef9c50_idx'),
        ),
    ]
