# Generated by Django 4.2.27 on 2026-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_reportlisting'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usedbikelisting',
            name='marketplace_status_193e1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='usedbikelisting',
            name='marketplace_seller__e8f48f_idx',
        ),
        migrations.RemoveIndex(
            model_name='usedbikelisting',
            name='marketplace_status_d22f63_idx',
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['status', 'is_verified'], name='marketplace_status_29976f_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['location_city', 'category'], name='marketplace_locatio_1d8167_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['price', 'created_at'], name='marketplace_price_7561f3_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['status', 'created_at'], name='marketplace_status_ae85fd_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['seller', 'created_at'], name='marketplace_seller__5044fa_idx'),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['status', 'location_city', 'created_at'], name='marketplace_status_7011a0_idx'),
        ),
    ]
