# Generated by Django 4.2.27 on 2026-02-13 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_alter_listingimage_compressed_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbikelisting',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedbikelisting',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedbikelisting',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike_reviews_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
