# Generated by Django 4.2.27 on 2026-03-13 17:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_usedbikelisting_marketplace_status_193e1b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbikelisting',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='usedbikelisting',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='marketplace_search__1da263_gin'),
        ),
    ]
