# Generated by Django 4.2.27 on 2026-02-17 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0003_usedbikelisting_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbikelisting',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Seller contact number for this listing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usedbikelisting',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usedbikelisting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('sold', 'Sold'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
