# Generated by Django 4.2.27 on 2026-02-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_usedbikelisting_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbikelisting',
            name='category',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('naked', 'Naked Sport'), ('cruiser', 'Cruiser'), ('commuter', 'Commuter'), ('scooter', 'Scooter'), ('adventure', 'Adventure'), ('cafe_racer', 'Cafe Racer'), ('offroad', 'Off-Road')], default='commuter', help_text='Bike category (e.g. Sports, Commuter)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usedbikelisting',
            index=models.Index(fields=['category', 'status'], name='marketplace_categor_0af89d_idx'),
        ),
    ]
