# Generated by Django 4.2.27 on 2026-03-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_usedbikelisting_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbikelisting',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedbikelisting',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
