# Generated by Django 4.2.27 on 2026-03-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_usedbikelisting_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbikelisting',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Whatsapp number for quick contact', max_length=20, null=True),
        ),
    ]
