# Generated by Django 4.2.27 on 2026-03-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_usedbikelisting_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbikelisting',
            name='engine_cc',
            field=models.IntegerField(blank=True, help_text='Engine capacity in CC', null=True),
        ),
        migrations.AddField(
            model_name='usedbikelisting',
            name='modifications',
            field=models.TextField(blank=True, help_text='List any modifications', null=True),
        ),
    ]
