# Generated by Django 4.2.27 on 2026-03-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_usedbikelisting_engine_cc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedbikelisting',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in BDT', max_digits=12),
        ),
    ]
