# Generated by Django 4.2.27 on 2026-04-18 08:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0008_shop_usedbikelisting_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('normal', 'Normal Member'), ('vip', 'VIP Member')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('boost_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_bikes', models.IntegerField()),
                ('badge_label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usedbikelisting',
            options={'ordering': ['-active_boost__valid_until', '-created_at']},
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10)),
                ('txid', models.CharField(max_length=100)),
                ('screenshot', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.membershipplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10)),
                ('txid', models.CharField(max_length=100)),
                ('screenshot', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('amount', models.DecimalField(decimal_places=2, default=80.0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='marketplace.usedbikelisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.usermembership'),
        ),
        migrations.AddField(
            model_name='usedbikelisting',
            name='active_boost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_listing', to='marketplace.listingboost'),
        ),
    ]
