# Generated by Django 4.2.27 on 2026-04-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_membershipplan_alter_usedbikelisting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='verification_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
