# Generated by Django 4.2.16 on 2026-06-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_shop_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cover_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
