from rest_framework import serializers
from .models import UsedBikeListing, ListingImage
from apps.bikes.serializers import BikeModelCompactSerializer
from apps.bikes.models import BikeModel

class ListingImageSerializer(serializers.ModelSerializer):
    url = serializers.ReadOnlyField(source='get_best_url')
    compression_ratio = serializers.ReadOnlyField()

    class Meta:
        model = ListingImage
        fields = [
            'id', 'original_image', 'webp_image', 'compressed_image', 
            'url', 'is_primary', 'order', 'compression_ratio',
            'file_size_original', 'file_size_webp'
        ]
        read_only_fields = ['webp_image', 'compressed_image', 'file_size_original', 'file_size_webp']

class UsedBikeListingSerializer(serializers.ModelSerializer):
    seller_name = serializers.ReadOnlyField(source='seller.username')
    seller_phone = serializers.SerializerMethodField()
    seller_location = serializers.ReadOnlyField(source='location')
    bike_details = BikeModelCompactSerializer(source='bike_model', read_only=True)
    images = ListingImageSerializer(many=True, read_only=True)
    
    # Computed fields for admin panel
    bike_model_name = serializers.SerializerMethodField()
    brand = serializers.SerializerMethodField()
    year = serializers.ReadOnlyField(source='manufacturing_year')
    image_url = serializers.SerializerMethodField()
    
    class Meta:
        model = UsedBikeListing
        fields = '__all__'
        read_only_fields = ['views_count', 'is_verified', 'created_at']

    def get_seller_phone(self, obj):
        return getattr(obj.seller, 'phone', None) or ''
    
    def get_bike_model_name(self, obj):
        if obj.bike_model:
            return obj.bike_model.name
        return obj.custom_model or obj.title
    
    def get_brand(self, obj):
        if obj.bike_model and obj.bike_model.brand:
            return obj.bike_model.brand.name
        return obj.custom_brand or 'Unknown'
    
    def get_image_url(self, obj):
        primary_image = obj.images.filter(is_primary=True).first()
        if not primary_image:
            primary_image = obj.images.first()
        if primary_image:
            return primary_image.get_best_url
        return None


class UsedBikeListingCreateSerializer(serializers.ModelSerializer):
    uploaded_images = serializers.ListField(
        child=serializers.ImageField(max_length=1000000, allow_empty_file=False, use_url=False),
        write_only=True,
        required=False
    )
    
    # Make bike_model optional since users can provide custom brand/model
    bike_model = serializers.PrimaryKeyRelatedField(
        queryset=BikeModel.objects.all(),
        required=False,
        allow_null=True
    )

    class Meta:
        model = UsedBikeListing
        exclude = ['seller', 'views_count', 'is_verified', 'created_at', 'updated_at']
        extra_kwargs = {
            'custom_brand': {'required': False},
            'custom_model': {'required': False},
            'registration_year': {'required': False},
            'is_featured': {'required': False},
            'is_urgent': {'required': False},
            'status': {'required': False},
        }

    def validate(self, data):
        # At least one of bike_model or custom_brand+custom_model must be provided
        bike_model = data.get('bike_model')
        custom_brand = data.get('custom_brand')
        custom_model = data.get('custom_model')
        
        if not bike_model and not (custom_brand or custom_model):
            # If no bike_model and no custom info, that's okay for now
            # The title is already generated by frontend
            pass
        
        return data

    def create(self, validated_data):
        images_data = validated_data.pop('uploaded_images', [])
        
        # Ensure we have a default for status if not provided
        if 'status' not in validated_data:
            validated_data['status'] = 'pending'
            
        listing = UsedBikeListing.objects.create(**validated_data)
        
        for i, image in enumerate(images_data):
            ListingImage.objects.create(
                listing=listing,
                original_image=image,
                is_primary=(i == 0),
                order=i
            )
        return listing
