from rest_framework import serializers
from .models import UsedBikeListing, ListingImage
from apps.bikes.serializers import BikeModelCompactSerializer
from apps.bikes.models import BikeModel
from apps.core.validators import DataValidator

class ListingImageSerializer(serializers.ModelSerializer):
    url = serializers.ReadOnlyField(source='get_best_url')
    compression_ratio = serializers.ReadOnlyField()

    class Meta:
        model = ListingImage
        fields = [
            'id', 'original_image', 'webp_image', 'compressed_image', 
            'url', 'is_primary', 'order', 'compression_ratio',
            'file_size_original', 'file_size_webp'
        ]
        read_only_fields = ['webp_image', 'compressed_image', 'file_size_original', 'file_size_webp']

class UsedBikeListingSerializer(serializers.ModelSerializer):
    seller_name = serializers.ReadOnlyField(source='seller.username')
    seller_phone = serializers.SerializerMethodField()
    seller_location = serializers.ReadOnlyField(source='location')
    bike_details = serializers.SerializerMethodField()
    images = ListingImageSerializer(many=True, read_only=True)
    
    # Computed fields for admin panel
    bike_model_name = serializers.SerializerMethodField()
    brand_name = serializers.SerializerMethodField()
    year = serializers.ReadOnlyField(source='manufacturing_year')
    image_url = serializers.SerializerMethodField()
    
    class Meta:
        model = UsedBikeListing
        fields = '__all__'
        read_only_fields = [
            'views_count', 'is_verified', 'created_at', 'updated_at',
            'rejection_reason', 'reviewed_at', 'reviewed_by'
        ]

    def get_seller_phone(self, obj):
        return getattr(obj.seller, 'phone', None) or ''

    def get_bike_details(self, obj):
        if not obj.bike_model_id:
            return None
        try:
            bike = BikeModel.objects.get(pk=obj.bike_model_id)
            return BikeModelCompactSerializer(bike).data
        except BikeModel.DoesNotExist:
            return None

    def get_bike_model_name(self, obj):
        if obj.bike_model_id:
            try:
                bike = BikeModel.objects.get(pk=obj.bike_model_id)
                return bike.name
            except BikeModel.DoesNotExist:
                pass
        return obj.custom_model or obj.title
    
    def get_brand_name(self, obj):
        if obj.bike_model_id:
            try:
                bike = BikeModel.objects.select_related('brand').get(pk=obj.bike_model_id)
                if bike.brand:
                    return bike.brand.name
            except BikeModel.DoesNotExist:
                pass
        return obj.custom_brand or 'Unknown'
    
    def get_image_url(self, obj):
        primary_image = obj.images.filter(is_primary=True).first()
        if not primary_image:
            primary_image = obj.images.first()
        if primary_image:
            return primary_image.get_best_url
        return None


class UsedBikeListingCreateSerializer(serializers.ModelSerializer):
    uploaded_images = serializers.ListField(
        child=serializers.ImageField(max_length=1000000, allow_empty_file=False, use_url=False),
        write_only=True,
        required=False
    )
    
    # Make bike_model optional since users can provide custom brand/model
    bike_model_id = serializers.IntegerField(
        required=False,
        allow_null=True
    )

    class Meta:
        model = UsedBikeListing
        exclude = [
            'seller', 'views_count', 'is_verified', 'created_at', 'updated_at',
            'rejection_reason', 'reviewed_at', 'reviewed_by',
            'status',  # Status is ALWAYS forced to 'pending' by the view's perform_create
        ]
        extra_kwargs = {
            'custom_brand': {'required': False},
            'custom_model': {'required': False},
            'registration_year': {'required': False},
            'is_featured': {'required': False},
            'is_urgent': {'required': False},
            'contact_number': {'required': True},
        }

    def validate_contact_number(self, value):
        return DataValidator.validate_phone(value)

    def validate(self, data):
        # At least one of bike_model_id or custom_brand+custom_model must be provided
        bike_model_id = data.get('bike_model_id')
        custom_brand = data.get('custom_brand')
        custom_model = data.get('custom_model')
        
        if not bike_model_id and not (custom_brand or custom_model):
            # If no bike_model and no custom info, that's okay for now
            # The title is already generated by frontend
            pass
        
        # Sanitize all inputs
        return DataValidator.sanitize_dict(data)

    def create(self, validated_data):
        images_data = validated_data.pop('uploaded_images', [])
        
        # Status is excluded from serializer fields and forced by the view's perform_create
        listing = UsedBikeListing.objects.create(**validated_data)
        
        for i, image in enumerate(images_data):
            # Process image from raw bytes before Cloudinary upload
            webp_file = None
            compressed_file = None
            try:
                from .image_processor import ImageProcessingService
                from django.core.files.base import ContentFile
                processed = ImageProcessingService.compress_and_convert(image)
                if processed.get('webp'):
                    webp_file = ContentFile(
                        processed['webp']['content'],
                        name=processed['webp']['name']
                    )
                if processed.get('compressed'):
                    compressed_file = ContentFile(
                        processed['compressed']['content'],
                        name=processed['compressed']['name']
                    )
                # Reset file pointer for original upload
                image.seek(0)
            except Exception as e:
                import logging
                logging.getLogger(__name__).warning(
                    "Image processing failed for listing %s: %s", listing.id, e
                )

            ListingImage.objects.create(
                listing=listing,
                original_image=image,
                webp_image=webp_file,
                compressed_image=compressed_file,
                is_primary=(i == 0),
                order=i,
                file_size_original=image.size if hasattr(image, 'size') else None,
            )
        return listing
