# Generated by Django 4.2.27 on 2026-03-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='totp_secret',
        ),
    ]
