# Generated by Django 4.2.27 on 2026-04-18 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('seller', 'Seller'), ('dealer', 'Dealer'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('staff_news', 'News Manager'), ('staff_used_bikes', 'Used Bikes Moderator'), ('staff_bikes', 'Official Bikes Manager'), ('staff_payments', 'Payments Reviewer'), ('staff_settings', 'Site Settings Manager')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(choices=[('staff_news', 'News Manager'), ('staff_used_bikes', 'Used Bikes Moderator'), ('staff_bikes', 'Official Bikes Manager'), ('staff_payments', 'Payments Reviewer'), ('staff_settings', 'Site Settings Manager')], max_length=30)),
                ('assigned_by_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
