# Generated by Django 4.2.27 on 2026-04-19 02:37

from django.db import migrations, models

def migrate_roles_to_sections(apps, schema_editor):
    StaffAdmin = apps.get_model('users', 'StaffAdmin')
    for staff in StaffAdmin.objects.all():
        if hasattr(staff, 'role_key') and staff.role_key:
            staff.sections = [staff.role_key]
            staff.save()

def reverse_migrate_roles_to_sections(apps, schema_editor):
    pass # Reverse data migration is lossy.

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role_staffadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffadmin',
            name='sections',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(migrate_roles_to_sections, reverse_code=reverse_migrate_roles_to_sections),
        migrations.RemoveField(
            model_name='staffadmin',
            name='role_key',
        ),
    ]
