# Generated by Django 4.2.27 on 2026-05-04 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0010_shop_verification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikes', '0014_bikemodel_avg_used_price_bikemodel_depreciation_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_segments', models.JSONField(default=list)),
                ('preferred_brands', models.JSONField(default=list)),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_displacement_min', models.IntegerField(blank=True, null=True)),
                ('preferred_displacement_max', models.IntegerField(blank=True, null=True)),
                ('new_vs_used_preference', models.FloatField(default=0.5)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_segment', models.CharField(blank=True, max_length=50, null=True)),
                ('trust_sensitivity', models.FloatField(default=0.7)),
                ('price_sensitivity', models.FloatField(default=0.5)),
                ('aspirational_index', models.FloatField(default=0.3)),
                ('avg_session_duration', models.FloatField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_searches', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('behavior_type', models.CharField(choices=[('view', 'View'), ('search', 'Search'), ('wishlist', 'Wishlist'), ('compare', 'Compare'), ('inquiry', 'Inquiry'), ('filter_apply', 'Filter Apply'), ('listing_view', 'Listing View')], max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bike_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.bikemodel')),
                ('used_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.usedbikelisting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'behavior_type', 'created_at'], name='recommendat_user_id_709200_idx'), models.Index(fields=['session_id', 'created_at'], name='recommendat_session_e6e9c8_idx'), models.Index(fields=['bike_model', 'behavior_type'], name='recommendat_bike_mo_cbe601_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('recommendations', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('context_bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.bikemodel')),
                ('context_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.usedbikelisting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'expires_at'], name='recommendat_session_2219be_idx'), models.Index(fields=['context_bike'], name='recommendat_context_de8458_idx')],
            },
        ),
    ]
