# Generated by Django 4.2.27 on 2026-01-31 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('naked', 'Naked Sport'), ('cruiser', 'Cruiser'), ('commuter', 'Commuter'), ('scooter', 'Scooter'), ('adventure', 'Adventure'), ('cafe_racer', 'Cafe Racer'), ('offroad', 'Off-Road')], max_length=20)),
                ('engine_capacity', models.IntegerField(help_text='Engine capacity in CC')),
                ('engine_type', models.CharField(blank=True, max_length=200, null=True)),
                ('max_power', models.CharField(blank=True, max_length=100, null=True)),
                ('max_torque', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_system', models.CharField(blank=True, max_length=100, null=True)),
                ('cooling_system', models.CharField(blank=True, max_length=100, null=True)),
                ('gears', models.IntegerField(default=5)),
                ('clutch_type', models.CharField(blank=True, max_length=100, null=True)),
                ('curb_weight', models.FloatField(blank=True, help_text='Weight in KG', null=True)),
                ('fuel_capacity', models.FloatField(blank=True, help_text='Capacity in Liters', null=True)),
                ('seat_height', models.FloatField(blank=True, help_text='Height in mm', null=True)),
                ('tyre_type', models.CharField(default='Tubeless', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current official price in BDT', max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('primary_image', models.URLField(blank=True, max_length=500, null=True)),
                ('popularity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='bikes.brand')),
            ],
            options={
                'ordering': ['-popularity_score', 'name'],
            },
        ),
    ]
