# Generated by Django 4.2.27 on 2026-03-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_bikemodel_primary_image_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemodel',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('naked', 'Naked Sport'), ('cruiser', 'Cruiser'), ('commuter', 'Commuter'), ('scooter', 'Scooter'), ('adventure', 'Adventure'), ('cafe_racer', 'Cafe Racer'), ('offroad', 'Off-Road')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='engine_capacity',
            field=models.IntegerField(db_index=True, help_text='Engine capacity in CC'),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Current official price in BDT', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bikevariant',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
    ]
