# Generated by Django 4.2.27 on 2026-03-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_bikemodel_image1_bikemodel_image2_bikemodel_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikespecification',
            name='mileage_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='mileage_highway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='top_speed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
