# Generated by Django 4.2.27 on 2026-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_bikespecification_mileage_city_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bikemodel',
            index=models.Index(fields=['-popularity_score', 'name'], name='bikes_bikem_popular_2c88a0_idx'),
        ),
        migrations.AddIndex(
            model_name='bikemodel',
            index=models.Index(fields=['brand', 'category', 'is_available'], name='bikes_bikem_brand_i_b09885_idx'),
        ),
        migrations.AddIndex(
            model_name='bikemodel',
            index=models.Index(fields=['price', 'engine_capacity'], name='bikes_bikem_price_eca00b_idx'),
        ),
    ]
