# Generated by Django 4.2.27 on 2026-03-13 17:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_bikemodel_bikes_bikem_popular_2c88a0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='bikemodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='bikes_bikem_search__ce297c_gin'),
        ),
    ]
