# Generated by Django 4.2.27 on 2026-03-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_bikemodel_meta_description_bikemodel_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikespecification',
            name='avg_fuel_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='cooling_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='distance_to_empty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='drls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='gear_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='gear_shift_pattern',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='projector_headlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='side_stand_cut_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='spark_plugs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='usb_charging',
            field=models.BooleanField(default=False),
        ),
    ]
