# Generated by Django 4.2.27 on 2026-03-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0009_bikespecification_avg_fuel_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikevariant',
            name='gps_navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikevariant',
            name='headlight_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikevariant',
            name='instrument_console',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikevariant',
            name='kerb_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bikevariant',
            name='mobile_connectivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikevariant',
            name='quick_shifter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikevariant',
            name='rear_brake_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikevariant',
            name='riding_modes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikevariant',
            name='seat_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikevariant',
            name='slipper_clutch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikevariant',
            name='traction_control',
            field=models.BooleanField(default=False),
        ),
    ]
