# Generated by Django 4.2.27 on 2026-03-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_bikevariant_gps_navigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
