# Generated by Django 4.2.27 on 2026-04-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0011_bikemodel_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCompetitorMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_aspirational', models.BooleanField(default=True, help_text='True if the competitor is a highly desired premium brand/model.')),
                ('competitor_bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_target', to='bikes.bikemodel')),
                ('source_bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_source', to='bikes.bikemodel')),
            ],
            options={
                'verbose_name_plural': 'Market Competitor Mappings',
                'unique_together': {('source_bike', 'competitor_bike')},
            },
        ),
    ]
