# Generated by Django 4.2.27 on 2026-04-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0012_marketcompetitormapping'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='bikes_brand_name_9f7848_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_popular'], name='bikes_brand_is_popu_380382_idx'),
        ),
    ]
