# Generated by Django 4.2.27 on 2026-05-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0013_brand_bikes_brand_name_9f7848_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='avg_used_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='depreciation_rate',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='segment',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_electric_focused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='trust_score',
            field=models.IntegerField(default=50, help_text='0-100 score for recommendation weight'),
        ),
    ]
