# Generated by Django 4.2.27 on 2026-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0014_bikemodel_avg_used_price_bikemodel_depreciation_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikevariant',
            name='image_url',
            field=models.CharField(blank=True, help_text='Specific image for this variant', max_length=500, null=True),
        ),
    ]
