# Generated by Django 4.2.16 on 2026-06-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0015_bikevariant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='official_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
