# Generated by Django 4.2.16 on 2026-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0016_brand_official_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='advantages',
            field=models.JSONField(blank=True, default=list, help_text='List of strings representing pros'),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='disadvantages',
            field=models.JSONField(blank=True, default=list, help_text='List of strings representing cons'),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts: [{'question': '...', 'answer': '...'}]"),
        ),
    ]
