# Generated by Django 4.2.16 on 2026-06-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0017_bikemodel_advantages_bikemodel_disadvantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikespecification',
            name='abs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='mileage_arai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikespecification',
            name='wheel_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
