# Generated by Django 4.2.27 on 2026-03-16 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikes', '0011_bikemodel_average_rating'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='bike_model',
            new_name='bike',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='bike_model',
            new_name='bike',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('bike', 'user')},
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'bike')},
        ),
    ]
