# Generated by Django 4.2.27 on 2026-04-04 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikes', '0012_marketcompetitormapping'),
        ('interactions', '0002_rename_bike_model_review_bike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViewHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('bike_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='bikes.bikemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_viewed'],
                'unique_together': {('user', 'bike_model')},
            },
        ),
    ]
