# Generated by Django 4.2.27 on 2026-02-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
